"""nuevas tablas

Revision ID: 3766439c8524
Revises: 774f8cba7957
Create Date: 2024-06-13 11:15:13.633893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3766439c8524'
down_revision: Union[str, None] = '774f8cba7957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categorias_descripcion', table_name='categorias')
    op.drop_index('ix_categorias_nombre', table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categorias_nombre', 'categorias', ['nombre'], unique=False)
    op.create_index('ix_categorias_descripcion', 'categorias', ['descripcion'], unique=False)
    # ### end Alembic commands ###
